name: push

on:
  push:
    branches:
      - main
    paths:
      - 'notifications/src/top_news_to_mm/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  arn: ${{ secrets.AWS_ROLE_ARN }}
  regis: ${{ secrets.ECR_REGISTRY }}
  repos: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v3

      - name: aws login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.arn }}
          aws-region: ap-northeast-1

      - name: registory login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.regis }}

      - name: build & push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./notifications/src/top_news_to_mm
          file: ./notifications/src/top_news_to_mm/Dockerfile
          tags: ${{ env.regis }}/${{ env.repos }}:"tag"
          cache-from: type=gha
          cache-to: type=gha,mode=max
